name: Update RVDSS Data

on:
  workflow_dispatch:
  schedule:
    # friday 11:00 america/toronto (16:00 utc during standard time)
    - cron: '0 16 * * FRI'
    # friday 15:00 america/toronto (20:00 utc during standard time)
    - cron: '0 20 * * FRI'


jobs:
  build:
    runs-on: ubuntu-22.04 # R not supported for ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      
      - name: Install Dependencies
        run: pip install -r scripts/requirements.txt
      
      - name: Download latest data
        run: python scripts/rvdss_update.py

      - name: Add new files
        run: git add target-data/  # This ensures the new 'data/' directory and its contents are added to the git index
      
      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -am 'update rvdss data' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
